# Generated by Django 4.2.6 on 2023-10-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "action_name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occurence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurence_date", models.DateTimeField(verbose_name="date field")),
                (
                    "action_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.action"
                    ),
                ),
            ],
        ),
    ]
